import React, { useEffect } from "react";
import Head from "next/head";
import { useHeader } from "hoc/withHeader";
import ProductsCollections from "./ProductsCollectionsView";
import ProductsHeader from "components/products/header";

export default function ProductsCollectionssContainer() {
  const { openHeader } = useHeader();
  useEffect(() => {
    openHeader({
      component: () => <ProductsHeader title={"Collections"} />,
    });
  }, []);
  return (
    <>
      <Head>
        <title>Products Collections | App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductsCollections />
    </>
  );
}
