import Head from "next/head";
import VideoSlug from "./VideoSlug";

export default function VideoSlugContainer() {
  return (
    <>
      <Head>
        <title>Video Detail | Collections</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VideoSlug/>
    </>
  );
}
